query AllPools($chain: GqlChain!, $first: Int, $skip: Int) {
  poolGetPools(where: { chainIn: [$chain] }, first: $first, skip: $skip) {
    address
    symbol
    dynamicData {
      swapEnabled
    }
  }
}
