query AllPools($chain: GqlChain!) {
  poolGetPools(where: { chainIn: [$chain] }) {
    address
    symbol
    tags
    protocolVersion
    dynamicData {
      swapEnabled
    }
    poolTokens {
      address
      isErc4626
    }
  }
}
