query AllGauges($chain: GqlChain!, $first: Int, $skip: Int) {
  poolGetPools(where: { chainIn: [$chain] }, first: $first, skip: $skip) {
    staking {
      gauge {
        gaugeAddress
        otherGauges {
          id
        }
      }
    }
    chain
    symbol
  }
}
