query GetHistoricalTokenPrices($addresses: [String!]!, $chain: GqlChain!, $range: GqlTokenChartDataRange!) {
  tokenGetHistoricalPrices(addresses: $addresses, chain: $chain, range: $range) {
    address
    chain
    prices {
      timestamp
      price
      updatedAt
      updatedBy
    }
  }
}
