query PoolSnapshot($id: String!, $ts_gt: Int, $ts_lt: Int) {
  poolSnapshots(where: { pool: $id, timestamp_gt: $ts_gt, timestamp_lt: $ts_lt}) {
    totalProtocolSwapFees
    totalProtocolYieldFees
    pool {
      tokens {
        address
      }
    }
  }
}
