query PoolsSnapshots($first: Int, $skip: Int, $block: Int) {
  poolSnapshots(
    first: $first
    skip: $skip
    orderBy: timestamp
    orderDirection: desc
    block: { number: $block }
    where: { protocolFee_not: null }
  ) {
    pool {
      address
      id
      symbol
      totalProtocolFeePaidInBPT
      totalProtocolFee
      tokens {
        symbol
        address
        paidProtocolFees
      }
    }
    timestamp
    protocolFee
    swapFees
    swapVolume
    liquidity
  }
}
