query PoolsSnapshots($first: Int, $skip: Int, $block: Int) {
  poolSnapshots(
    first: $first
    skip: $skip
    orderBy: timestamp
    orderDirection: desc
    block: { number: $block }
  ) {
    pool {
      address
      id
      symbol
      totalProtocolFeePaidInBPT
      tokens {
        symbol
        address
        paidProtocolFees
      }
    }
    timestamp
  }
}
