name: Python package
permissions:
  contents: read

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bal_tools/requirements.txt
      - name: Test with pytest
        env:
          DRPC_KEY: ${{ secrets.DRPC_KEY }}
          GRAPH_API_KEY: ${{ secrets.GRAPH_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: |
          pip install -r bal_tools/requirements-dev.txt
          pytest -x
